### ISSUE TITLE
Proposed New BB4_P12 (Book 4 pp. 24, 25, 26) and thereafter ...

### ISSUE THREAD

**Issue by rryman** [rryman/BB4-Worksheets#18]
Here is my suggested format for the new page 12 in the BB4 worksheets:
[BB4_P12.pdf](https://github.com/rryman/BB4-Worksheets/files/2496549/BB4_P12.pdf)

If you agree with this layout and content, I will continue with the new page 13.
It would contain similar layout and content using info from pages 27 and 28 of Book 4.

New page 14 could be the stage plans from Book 4 pages 30 and 32 (without the notation below them).
The instructions would be something like:
Notate the appropriate stage location, travel, and direction signs below the stage plans.

New page 15 would be the same as the new page 14 using the stage plans from Book 4 pages 34 and 36.

New page 16 would have to have a bit of an explanation of diagonal travel - then we could use the examples from Book 4 pages 40, 41, and 42. Not sure if that will all fit on one page. I could mock it up, but I want to make sure I am on the right track before proceeding.

If so, new page 17 could be examples from Book 4 pages 43, 44, and 45.

**Comment by rsryman** [comment]
Layout looks good. I have created pp. 12-13 based on your framework re BB4 pp. 24-28, BUT I have spaced the page a bit more, since there is room. Let me know if you prefer me to match your BB4_P12.pdf exactly.

New pp. 14-15 updated as per your suggestion re BB4, pp. 30&32, 34&36. Again, this approach tests theory understanding more so than writing skill, but I thinks it's OK here out of context. Students will have a chance to copy below-stave info at the correct scale when they get to CH 6.

Re Diagonal Travel, see new pp. 16-17 (BB4 pp. 37-45), based on new pp. 12-13 (BB4 pp.25-28). WERE IS YOUR COMMENT RE TAKING OUT THEORY EXPLANATIONS FROM WORKSHEETS?
