### ISSUE TITLE
BB4New LayoutForP28

### ISSUE THREAD

**Issue by rsryman** [rryman/BB4-Worksheets#54]
This page was so full we had to bump the note to p. 27. 

I don't know if we could save enough space to move the note to p. 28, but we could free up a bit of space by taking out the empty staves 2 and 6, and add the instruction at the top of the page: 

Below are two alternate ways to notate each sequence. In the empty staves copy either version.

See suggested revision:
[BB4WorksheetP28Feb3,2019.pdf](https://github.com/rryman/BB4-Worksheets/files/2825997/BB4WorksheetP28Feb3.2019.pdf)

**Comment by rryman** [comment]
I like this idea. In worksheets for Book 4 I think we should do this where-ever possible rather than have them copy similar notation lots of times.

What about encouraging them to use repeat signs? i.e., something like ...
In the empty staves copy the _repeat_ sign version.
Or 
In the empty staves copy the version that uses _repeat_ signs.

**Comment by rsryman** [comment]
Then why show both versions? Maybe:
Below are two ways to notate each sequence: without then with _repeat_ signs. In the empty staves copy either version.

**Comment by rryman** [comment]
Okay. Let's go with:
Below are two ways to notate each sequence: without then with _repeat_ signs. In the empty stave [delete "s"?] copy either version.

Hopefully things like the missing bar line will something you pick up as your proofread the .doc file before I start editing the pdf with Adobe Illustrator. Please also be on the look out for reduced notation as I am not sure I caught them all as I went through it quickly.  Thanks!
